HR = 'hr'
EN = 'en'

LOAD = 'load'
UNLOAD = 'unload'

STARTING = 'starting'
DESTINATION = 'destination'

VEHICLE_TYPES = 'vehicle_types'
VEHICLE_TYPE = 'vehicle_type'
VEHICLE_UPGRADES = 'vehicle_upgrades'
VEHICLE_FEATURES = 'vehicle_features'
VEHICLE_EQUIPMENT = 'vehicle_equipment'
MIN_LENGTH = 'min_length'
MAX_LENGTH = 'max_length'
MIN_WEIGHT = 'min_weight'
MAX_WEIGHT = 'max_weight'
SHOW_BLOCKED_USERS = 'show_blocked_users'
AUCTION = 'auction'
MY_BID = 'my_bid'
STOCK_TYPES = 'stock_types'
STOCK_EQUIPMENTS = 'stock_equipments'
MIN_AREA = 'min_area'
MAX_AREA = 'max_area'
COUNTRIES = 'countries'
CITIES = 'cities'
ZIP_CODES = 'zip_codes'
COUNTRIES_FROM = 'countries_from'
COUNTRIES_TO = 'countries_to'
CITIES_TO = 'cities_to'
CITIES_FROM = 'cities_from'
ZIP_CODES_FROM = 'zip_codes_from'
ZIP_CODES_TO = 'zip_codes_to'
GOODS_FORMS = 'goods_forms'
GOODS_TYPES = 'goods_types'
TRANSPORT_TYPES = 'transport_types'
OWN_VEHICLES = 'own_vehicles'
LOADING_SYSTEMS = 'loading_systems'

DATE_FROM = 'date_from'
DATE_TO = 'date_to'
DATE = 'date'

NEXT_CURSOR = 'next_cursor'
LIMIT = 'limit'

ACTIVE = 'active'
CLOSED = 'closed'

STATUS = 'status'

NEED_CONFIRM = 'need_confirm'
REJECTED = 'rejected'

DEACTIVATE = 'deactivate'
UNAUTHORIZED = 'unauthorized'