# Generated by Django 3.2.6 on 2021-08-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='panes',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
