version: '3.3'

services:
  web:
    build: ./app
    # command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runsslserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 8045:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - 5438:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data: