# Generated by Django 3.2.6 on 2021-08-06 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('cargo_note', models.JSONField(blank=True, default=None, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('exchange', models.BooleanField(default=False)),
                ('vehicle_note', models.JSONField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('auction', models.BooleanField(default=False)),
                ('auction_end_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('contact_accounts', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('OIB', models.CharField(max_length=256)),
                ('web', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('address', models.CharField(max_length=512)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('native_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.city')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VehicleUpgradeTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, choices=[('hr', 'Hrvatski'), ('en', 'Engleski')], default=None, max_length=6, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('vehicle_upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicleupgrade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleTypeTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, choices=[('hr', 'Hrvatski'), ('en', 'Engleski')], default=None, max_length=6, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicletype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleFeatureTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, choices=[('hr', 'Hrvatski'), ('en', 'Engleski')], default=None, max_length=6, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('vehicle_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehiclefeature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsTypeTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, choices=[('hr', 'Hrvatski'), ('en', 'Engleski')], default=None, max_length=6, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('goods_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.goodstype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('lang', models.CharField(choices=[('hr', 'Hrvatski'), ('en', 'Engleski')], default='hr', max_length=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80, verbose_name='email')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBlockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('unblocked_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('blocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocked_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_company', to='transport.company')),
                ('my_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_company', to='transport.company')),
                ('unblocked_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unblocked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='countries',
            field=models.ManyToManyField(blank=True, to='transport.Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.country'),
        ),
        migrations.CreateModel(
            name='CargoLoadUnload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.cargo')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.country')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.zipcode')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='goods_types',
            field=models.ManyToManyField(blank=True, to='transport.GoodsType'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='vehicle_features',
            field=models.ManyToManyField(blank=True, to='transport.VehicleFeature'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, to='transport.VehicleType'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='vehicle_upgrades',
            field=models.ManyToManyField(blank=True, to='transport.VehicleUpgrade'),
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='transport.cargo')),
            ],
        ),
    ]
