# Generated by Django 3.2.6 on 2021-08-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='native_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
