# Generated by Django 3.2.6 on 2021-08-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_language_native_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.company'),
        ),
    ]
