# Generated by Django 3.2.6 on 2021-08-09 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0003_cargo_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_length', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('vehicle_load_capacity', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=11, null=True)),
                ('connected_vehicle_length', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('connected_vehicle_load_capacity', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=11, null=True)),
                ('vehicle_note', models.JSONField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_accounts', models.ManyToManyField(blank=True, related_name='loading_space_contact_accounts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_features', models.ManyToManyField(blank=True, to='transport.VehicleFeature')),
                ('vehicle_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vehicletype')),
                ('vehicle_upgrades', models.ManyToManyField(blank=True, to='transport.VehicleUpgrade')),
            ],
        ),
        migrations.AlterField(
            model_name='cargoloadunload',
            name='type',
            field=models.CharField(blank=True, choices=[('load', 'Utovar'), ('unload', 'Istovar')], default=None, max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='StartingPointDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('within_km', models.IntegerField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, choices=[('starting', 'Polazište'), ('destination', 'Odredište')], default=None, max_length=15, null=True)),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.city')),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.country')),
                ('loading_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.loadingspace')),
                ('zip_code', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.zipcode')),
            ],
        ),
    ]
