# Generated by Django 3.2.6 on 2021-08-09 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20210809_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingspace',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.company'),
        ),
    ]
