# Generated by Django 3.2.6 on 2021-08-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_stock_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='min_down_bind_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True),
        ),
    ]
