# Generated by Django 3.2.6 on 2021-08-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_cargo_min_down_bind_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alpha2Code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
