# Generated by Django 3.2.6 on 2021-08-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_stockimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockimage',
            name='stock',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.stock'),
        ),
    ]
