# Generated by Django 3.2.6 on 2021-08-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_stockimage_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockimage',
            name='title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
