# Generated by Django 3.2.6 on 2021-08-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_alter_stockimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoloadunload',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.city'),
        ),
        migrations.AlterField(
            model_name='cargoloadunload',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.country'),
        ),
        migrations.AlterField(
            model_name='cargoloadunload',
            name='zip_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.zipcode'),
        ),
    ]
