# Generated by Django 3.2.6 on 2021-08-26 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_auto_20210824_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('path', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AlterField(
            model_name='companymail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_emails', to='transport.company'),
        ),
        migrations.AlterField(
            model_name='companynumber',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_numbers', to='transport.company'),
        ),
    ]
