# Generated by Django 3.2.6 on 2021-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_companydocument_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
