# Generated by Django 3.2.6 on 2021-08-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_auto_20210827_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoadingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='goods_types',
            field=models.ManyToManyField(blank=True, to='transport.GoodsType'),
        ),
        migrations.AddField(
            model_name='company',
            name='own_vehicles',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, to='transport.VehicleType'),
        ),
        migrations.AddField(
            model_name='company',
            name='vehicle_upgrades',
            field=models.ManyToManyField(blank=True, to='transport.VehicleUpgrade'),
        ),
        migrations.AddField(
            model_name='company',
            name='vehicles_num',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='goods_forms',
            field=models.ManyToManyField(blank=True, to='transport.GoodsForm'),
        ),
        migrations.AddField(
            model_name='company',
            name='loading_systems',
            field=models.ManyToManyField(blank=True, to='transport.LoadingSystem'),
        ),
        migrations.AddField(
            model_name='company',
            name='transport_types',
            field=models.ManyToManyField(blank=True, to='transport.TransportType'),
        ),
    ]
