# Generated by Django 3.2.6 on 2021-08-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0020_auto_20210830_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockimage',
            old_name='image',
            new_name='path',
        ),
    ]
