# Generated by Django 3.2.6 on 2021-09-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0021_rename_image_stockimage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
