# Generated by Django 3.2.6 on 2021-09-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0022_company_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='countries',
            new_name='cover_countries',
        ),
    ]
