# Generated by Django 3.2.6 on 2021-09-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0023_rename_countries_company_cover_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='vehicle_equipment',
            field=models.ManyToManyField(blank=True, to='transport.VehicleEquipment'),
        ),
    ]
