# Generated by Django 3.2.6 on 2021-09-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0025_auto_20210904_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
