# Generated by Django 3.2.6 on 2021-09-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0026_companydocument_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_equipments',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_types',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_types',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
