# Generated by Django 3.2.6 on 2021-09-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0027_auto_20210908_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_equipments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
