# Generated by Django 3.2.6 on 2021-09-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0028_stock_stock_equipments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_equipments',
            new_name='stock_equipment',
        ),
    ]
