# Generated by Django 3.2.6 on 2021-09-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0032_company_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('need_confirm', 'need_confirm'), ('rejected', 'rejected')], default='need_confirm', max_length=15, null=True),
        ),
    ]
