# Generated by Django 3.2.7 on 2021-09-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0033_auto_20210914_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockimage',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
