# Generated by Django 3.2.7 on 2021-09-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0034_stockimage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='auction_notification_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
