# Generated by Django 3.2.7 on 2021-10-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0035_cargo_auction_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='closed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
