# Generated by Django 3.2.7 on 2021-10-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0037_auto_20211019_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alpha3Code',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='translations',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha2Code',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
