# Generated by Django 3.2.7 on 2021-11-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0039_language_alpha2code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
